### ISSUE TITLE
Can Printer Be Independent of LINQPad

### ISSUE THREAD

**Issue by sgoguen** [gusty/FsPad#1]
Is there any interest in having a printer doesn't require LINQPad to be installed?

I was working on one not long ago that looks something like this:  https://github.com/steego/Steego.NET/blob/master/Steego.Fs.WinDump/Printer.fs

**Comment by gusty** [comment]
Yes, that's definitely the next step.
Linqpad was a quick way to prototype it, but apart of getting rid of it, we need something that is more F# friendly, for instance when printing F# values like tuples.

I also started working on a pretty printer, but it's still in the early stages.

I just had a quick look to your project, there's no readme, what is it about?

**Comment by sgoguen** [comment]
The Steego.Fs.WinDump project is a basically a pretty printer.  I've been doing a bit of experimenting with pretty printing and explorable interfaces where object graphs are automatically explorable via URLs.

If you're working on a pretty printer, I'd be happy to help out with it.

What features do you imagine in a minimal viable printer?

**Comment by gusty** [comment]
I would like to have basically something like Linqpad.
With all features, including its default layout, way to expand/collapse, ability to detect recursive values, but with some F# friendliness for tuples, options and Discriminates Unions.

I will have a look at your project, and also share what I've done.
From what I see in the code you took the same HTML generation approach I did.

The main goal in this project is to share what I was using all these years at work to explore data, which is this script, plus some stuff from [F#+](https://github.com/gusty/FSharpPlus), plus some other exotic scripts I have to manipulate tuples, that all together makes a very quick way to query and explore data coming from DB, text files, logs, application output and so on.

**Comment by gusty** [comment]
I just downloaded your project, its printer is very different to the one in linqpad.

I can see you [recently added a floating browser](https://github.com/steego/Steego.NET/commit/ed6f25fb17914bdf251a4bd44099d7d446ec5b23) pretty much like the one here, what were you using before?

Also I see some linqpad stuff there, a linqpad file for example, what is all that stuff?

It looks very interesting. Can you explain what are the main differences with this project (apart from the fact that this one just started)?

**Comment by sgoguen** [comment]
>  just downloaded your project, its printer is very different to the one in linqpad.

It is.  I haven't been beholden to LINQPad's printer, but I'm not opposed to it either.  Is there anything that you find missing that you'd like to see?  Maybe you'd like to see it collapsable?  LINQPad like style?

> I can see you recently added a floating browser pretty much like the one here, what were you using before?

Before I did the floating browser (Inspired by you), I was playing with web sockets and a Suave server here:  https://github.com/steego/Steego.Demo

I actually have a few different incarnations of this idea throughout my repos.  The long and short of it is:  I've done a few versions of this thing, but just can't seem to mentally focus on one solution.  I tend to work late so I often lose momentum and abandon this side-project for a while.

> Also I see some linqpad stuff there, a linqpad file for example, what is all that stuff?

Are you talking about this?  https://github.com/steego/Steego.NET/tree/master/src/Steego.LinqPad

It's just an abandoned project where I was putting some code I was reusing in a NuGet package.

> It looks very interesting. Can you explain what are the main differences with this project (apart from the fact that this one just started)?

I saw your project and decided to adapt my printer to it as a first pass.  I don't really have any goals for it right now.  I think I wanted to kick it your way and see if you had any thoughts.  BTW, if any of my efforts help you, feel free to take from them what you like and leave out what you don't.  

I'm curious:  What key features would you like to have in a pretty printer?

**Comment by gusty** [comment]
I think the main difference with your pretty printer and linqpad is that yours is more 'pretty' whereas linqpad looks more like tabular data oriented, and that's what I want for this little project.

As I said it's just a tool I would use to quickly visualize data, mostly sequences of "something with fields".

If you could help me that will be great. I shared this project in the intent to join forces with other developers and eventually if it reaches a mature state and general interest, we can move it to FsProjects.

I'm working out an example of the pretty printer I've drafted to share it with you, it uses static constraints, but that's likely to change to a reflection based approach.

**Comment by gusty** [comment]
@sgoguen  Here's a [draft of what I have in mind](https://gist.github.com/gusty/96f4b36780f1fcf2200252ac1ce05074).
The relevant code is at the end of the file.
Also note that in addition to that I plan:
 - Discriminated unions, will be a key difference with Linqpad as they will be printed in a logical way.
 - Options will be treated specially, they would be a normal value with some distinctive style for Some's, and an empty cell for None's.
 - Result types might be treated specially as well.

Let me know what do you think !

**Comment by sgoguen** [comment]
This looks great!  I'm really glad you took the TypeShape approach for a number of reasons, one being it now gives me a reason to play with it some more.

If you decide to throw it in a development branch, I'd be very tempted to fork it and play with it.  (Ex:  I noticed it could use a little HTML encoding and very minor things like that)

Is there anywhere you'd like assistance?

**Comment by gusty** [comment]
Thanks, I will try to update the project.
Regarding the HTML generation, I was thinking in using an intermediate representation, I think you did a similar approach in your project.
Typeshape simplifies all the reflection stuff, but we might not need it in the future, I don't know at this point, but at the moment it makes sense. Nonetheless it's nice library to play with. 
Your contribution will be much appreciated !

**Comment by sgoguen** [comment]
I forked this project and added the .fsx file to my fork and then I started experimenting with this example:

```fsharp
//  Recursively Defined Object
type Tree<'a>(value:'a, getEdges:'a -> seq<'a>) = 
    let list = lazy [ for e in getEdges(value) -> Tree(e, getEdges) ]
    member this.Value = value
    member this.Children = list.Value

let tree1 = Tree(1, fun x -> seq { for x in x..2 -> x })

Results.Dump tree1
```

I know you just started with your pretty printer, but I was curious what your thoughts were regarding recursively defined types.  Historically, my first fix for this is to add a maxLevel parameter to my pretty printer and go from there.  One could update the intermediate representation to:

```fsharp
type PrettyPrint =
    | List  of list<PrettyPrint>
    | Table of list<Field>
    | Value of string * string
    | MaxRecurse of Type * lazy PrettyPrint
```

I'm not actually suggesting it be updated to that representation, but rather I thought this idea might provoke some ideas on your side.

In any event, I'll play with this idea for now.  Please let me know if you have a better idea.

**Comment by gusty** [comment]
Honestly I still didn't think about how to solve the deep nesting problem.

I know at some point I will have to deal with it, specially when reflecting over objects with cycles, or simply recursive DUs, like the Tree in your example, but I concentrated first in getting it working for simple values which is what you normally get back from DBs, parsing text files or web scrapping.

Adding a  ``MaxRecurse`` sounds definitely the way to go.

I think Linqpad has that approach, and also the Lazy (clickable) value. All complicated stuff and really a must have at some stage of the project.

I'm not wanting to spend too much of my time in those aspects at this stage, but if you want to, please go ahead, as I said, it's a must at some point.

What I want is to spend some time thinking about how to print options and DUs. If I have an update on that I'll let you know.

Good stuff, thanks !

**Comment by sgoguen** [comment]
Agreed.  I figured maxDepth will clamp off the issue for now.  After we
take care of basic value types, we can have a lot of fun with figuring out
how to do interactive types like lazy types, observables, dump containers,
etc.

**Comment by sgoguen** [comment]
Made this quick change to the printer to clamp off recursion issues.

[Recursive Support commit](https://github.com/sgoguen/FsPad/commit/92f9fed9a65f32f0e08f0889c3de3d90ace229f2)

The main idea is I changed the "pretty printer" type from 'T -> PrettyPrint to this:

```fsharp
type PrettyPrinter<'T> = int -> 'T -> PrettyPrint
```

I then added a helper function called wrapNested that returns a MaxRecurse if the level dips below 1.

```fsharp
let wrapNested(p : PrettyPrinter<'a>) = unbox<PrettyPrinter<'T>>(fun level x -> if level <= 0 then MaxRecurse else p level x)
```

Again, this just clamps off the issues.  I'd love to hear your ideas on recursion strategies and context when it becomes more relevant.

**Comment by gusty** [comment]
Cool, do a PR whenever you want !

**Comment by gusty** [comment]
Thanks ! 
I was playing a bit and looks like at this point we can safely close this issue and get rid of Linqpad.
There are more stuff Linqpad provides but we can slowly get there.
I'll keep playing and see if I can come up with a more accurate design and eventually a roadmap.
One question at this point, is whether we should pack it in a dll or keep it as a (long) script.
What do you think?

**Comment by sgoguen** [comment]
> One question at this point, is whether we should pack it in a dll or keep it as a (long) script.
What do you think?

I was going to ask you the same thing.  :)  Honestly, I think both have value and I was wondering if a build script that generates a single .fsx file (which gets committed to the repo) might be a nice option.  I'm good with deferring this for now.

**Comment by gusty** [comment]
Another thing to consider, for this decision, is portability.
I used to think that a script is more portable, but now with netstandard I have the impression that is the opposite.
I would say let's aim for a .dll for now but as you say, the built script will be also a nice to have.

**Comment by sgoguen** [comment]
Let's do it.  I'll set it up like FSharpPlus.  Seeing how it will be .NET Standard, I separate the printing modules from the Windows form module.  This works for me because I'd like the option to host the printer on a web server.

**Comment by gusty** [comment]
Well done !
I did some cleanup there.

>  I'd like the option to host the printer on a web server.

I never thought about it, it's certainly a good idea but we'll need to review the code in order to take into account some extra considerations (performance, thread safe).

Anyway I think the interactive should also be packed in a dll. Maybe we can generate two dlls? One only with the Printer and another one with both, Printer + Interactive.

We could use staticlink, but right now there is an issue and it's not working for .NetStandard

**Comment by gusty** [comment]
I'm not very happy with the fact that both the script and the .fs file are checked in source control.
After changes one will be outdated or changes had to be replicated in both which will polute the history with duplication in updates.

I think one of them has to be excluded from the source control, I guess the easiest is the fsx, since ti's the one being generates, but may be is better the other way.

**Comment by sgoguen** [comment]
That makes sense.  I kept the .fsx script because I wasn't sure if you liked the option of referencing the .fsx file with Paket.

**Comment by gusty** [comment]
Actually I do like it.

I think the ideal scenario is maybe to have the .fsx as master and checked in and from that file generate the source files in the build process.

Another alternative is to have exactly the opposite, the .fsx not checked in, and it will be generated as part of the build process.

Both cases will allow to have it referenced from Paket.

**Comment by sgoguen** [comment]
I get it.  Keep it as an .fsx for now to make is cheap and easy to play with it.

Are you thinking about using some sort of file separator in the master .fsx with the idea you'd split on it and write to the respective .fs files?

**Comment by gusty** [comment]
Yes. But I'm also thinking that would defeat the wholepoint of having the source files.
Maybe we should abandon the sources for now, until we have something more decent to release.
